version: "3.8"
services:
  openresty:
    image: openresty-gateway:lastest
    container_name: openresty 
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./lua:/usr/local/openresty/nginx/lua
      - ../logs:/usr/local/openresty/nginx/logs
      - ../upload_root:/usr/local/openresty/nginx/html/upload:rw
    ports:
      - "10000:80"
    build:
      context: .
    environment: 
      TZ: Asia/Shanghaids
      JWT_KEY: ZW1selpHOHVjSEp2WjNKbGMzTXVhWE53YjNKMGN3

